<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Crossbows-MacBook-Pro.local" ignored="0" name="Default test" tests="8" failures="1" timestamp="27 Jun 2018 20:34:55 GMT" time="31.328" errors="0">
  <testcase name="homePageLogin" time="3.999" classname="com.ecom.qa.testcases.LoginPageTest"/>
  <testcase name="apiTestReadUsersList001" time="0.638" classname="com.ecom.qa.testcases.ApiCallsTest"/>
  <testcase name="homePageLogout" time="6.212" classname="com.ecom.qa.testcases.LoginPageTest"/>
  <testcase name="apiTestReadUsersList002" time="0.409" classname="com.ecom.qa.testcases.ApiCallsTest">
    <failure type="java.lang.AssertionError" message="Eve is found in response **Expected failure**">
      <![CDATA[java.lang.AssertionError: Eve is found in response **Expected failure**
at org.testng.Assert.fail(Assert.java:96)
at com.ecom.qa.testcases.ApiCallsTest.apiTestReadUsersList002(ApiCallsTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- apiTestReadUsersList002 -->
  <testcase name="quickView" time="1.289" classname="com.ecom.qa.testcases.LoginPageTest"/>
  <testcase name="apiTestCreateUser003" time="0.409" classname="com.ecom.qa.testcases.ApiCallsTest"/>
  <testcase name="apiTestUpdateUser004" time="0.323" classname="com.ecom.qa.testcases.ApiCallsTest"/>
  <testcase name="apiTestDeleteUser005" time="0.34" classname="com.ecom.qa.testcases.ApiCallsTest"/>
</testsuite> <!-- Default test -->
